name: thinkcard
description: "Social media"
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  image_picker: ^1.1.2
  lucide_icons: ^0.257.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.1
  flutter_animate: ^4.5.0
  sign_in_with_apple: ^6.1.1
  custom_refresh_indicator: ^3.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: assets/logos/logo_1152px.png
  adaptive_icon_background: assets/logos/logo_1152px_adaptive.png
  adaptive_icon_foreground: assets/logos/logo_1152px_adaptive.png
  min_sdk_android: 26
  